name: build for windows
on: [push]

jobs:
  build:

    runs-on: Windows
    steps:
      - uses: actions/checkout@v3
      
      - name: "Windows: Cygwin download"
  if: runner.os == 'Windows'
  run: |
    Invoke-WebRequest 'https://cygwin.com/setup-x86_64.exe' -OutFile 'setup-x86_64.exe'

    - name: "Windows: Cygwin setup"
    if: runner.os == 'Windows'
  # The setup does not complete properly in powershell for some reason
  shell: cmd
        run:.\setup-x86_64.exe --quiet-mode --site http://cygwin.mirror.constant.com --symlink-type=sys --packages mingw64-i686-binutils=2.37-2,mingw64-x86_64-binutils=2.37-2,curl,diffutils,git,m4,make,mercurial,mingw64-i686-gcc-core,mingw64-i686-gcc-g++,mingw64-x86_64-gcc-core,mingw64-x86_64-gcc-g++,patch,perl,rsync,unzip
        - name: Set up GCC
            uses: egor-tensin/setup-gcc@v1
            with:
              version: latest
              platform: x64

        - name: Build
            run: gcc -o CakeEdit.elf CakeEdit.c -Wall -Werror -Wextra
        - name: Upload as artefact
            uses: actions/upload-artifact@v2 
        with:
          name: CakeEdit
          path: CakeEdit.exe
- name: Cache
  uses: actions/cache@v3.2.6
  with:
    # A list of files, directories, and wildcard patterns to cache and restore
    path: 
    # An explicit key for restoring and saving the cache
    key: 
    # An ordered list of keys to use for restoring stale cache if no cache hit occurred for key. Note `cache-hit` returns false in this case.
    restore-keys: # optional
    # The chunk size used to split up large files during upload, in bytes
    upload-chunk-size: # optional
    # An optional boolean when enabled, allows windows runners to save or restore caches that can be restored or saved respectively on other platforms
    enableCrossOsArchive: # optional, default is false
    # Fail the workflow if cache entry is not found
    fail-on-cache-miss: # optional, default is false



